version: "3.9"
# limitation:
# - we are able to run SE_NODE_MAX_SESSIONS session not more than cpu core we have (cpu limit)
# - each node uses approximately 2x250MB of RAM
# - each node uses approximately 256 MB of SSD disk space
services:
  e2e:
    image: gradle:7.5.1-jdk17
    working_dir: /code
    volumes:
      - ./:/code
      - downloads:/code/downloads
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - selenium-hub
      - chrome
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:4.5.0-20220929
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
    environment:
      - TZ=Europe/Berlin
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_SESSION_RETRY_INTERVAL=5
  chrome:
    image: selenium/node-chrome
    shm_size: 512m
    volumes:
      - downloads:/home/seluser/
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - TZ=Europe/Berlin
volumes:
  downloads: