name: CI e2e space test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run e2e tests
        env:
          E2E_TITLE: e2e-github-space
          E2E_WEB_URL: https://e2e.jetbrains.space/p/e2e/
          E2E_TEST_SUITE: e2e.xml
        timeout-minutes: 10
        run: docker-compose up e2e
        working-directory: .