# This is a basic workflow which starts end-to-end tests on GitHub actions
name: e2e

# Controls when the workflow will run
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      # Runs gradle e2e
      - name: Runs gradle e2e
        timeout-minutes: 10
        run: ./gradlew e2e

      # Upload e2e test result as artifact on GitHub
      - name: Upload e2e test result as artifact on GitHub
        uses: actions/upload-artifact@v3
        with:
          name: e2e_reports
          path: ./build/reports/tests/e2e/e2e/